# This file may be used to create an environment using:

name: attention_exoplanets

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.6

- pip:

async-generator           1.10
async-timeout             3.0.1
attrs                     20.3.0
autograd                  1.3
backcall                  0.2.0
batman-package            2.4.9
comet-ml                  3.8.1
Cython                    0.29.24
dataclasses               0.8
decorator                 4.4.2
GaPP                      1.0
google                    3.0.0
google-auth               1.28.1
google-auth-oauthlib      0.4.4
google-pasta              0.2.0
grpcio                    1.32.0
h5py                      2.10.0
html5lib                  0.9999999
importlib-metadata        3.7.3
iniconfig                 1.1.1
install                   1.3.4
ipykernel                 5.5.0
ipython                   7.16.2
ipython-genutils          0.2.0
ipywidgets                7.6.3
Markdown                  3.3.4
MarkupSafe                1.1.1
matplotlib                3.3.4
memoization               0.3.2
mistune                   0.8.4
ml-metrics                0.1.4
numpy                     1.19.5
nvidia-ml-py3             7.352.0
pandas                    1.1.5
pickleshare               0.7.5
Pillow                    8.2.0
pip                       21.3.1
py                        1.10.0
pydl                      0.7.0
PySocks                   1.7.1
requests                  2.25.1
requests-oauthlib         1.3.0
requests-toolbelt         0.9.1
rsa                       4.7.2
scipy                     1.5.4
terminado                 0.9.3
test-tube                 0.7.5
testpath                  0.4.4
torch                     1.8.1
torchmetrics              0.2.0
torchtext                 0.9.1
tornado                   6.1
tqdm                      4.60.0
uncertainties             3.1.5
yarl                      1.6.3
zipp                      3.4.1